function generateCode(homebutton) {
  let params = {
      hbimage: homebutton,
      pcolor1: document.getElementById('colorPrimary1').value,
      pcolor1t: document.getElementById('colorPrimary1').value,
      pcolor2: document.getElementById('colorPrimary2').value,
      bg1: document.getElementById('NTBackgroundColor01').value,
      bg2: document.getElementById('NTBackgroundColor02').value,
      bg3: document.getElementById('NTBackgroundColor03').value
  }

  var code = "";

  code += ":root {\n";

  if(!(params.hbimage == "" || params.hbimage == null)) {
    code += `--HomeButtonImg: url('${params.hbimage}');\n`;
  }
  if(!(params.pcolor1 == "" || params.pcolor1 == null)) {
    code += `--primary: ${params.pcolor1};\n`;
  }
  if(!(params.pcolor1t == "" || params.pcolor1t == null)) {
    if(params.pcolor1t.substring(0,1) == "#"){
      params.pcolor1t = hexToRgbA(params.pcolor1t);
    } else if(params.pcolor1t.substring(0,4) == "rgb(") {
      params.pcolor1t = params.pcolor1t.replace(")",",.25)");
      params.pcolor1t = params.pcolor1t.replace("rgb(","rgba(");
    }
    code += `--primaryT: ${params.pcolor1t};\n`;
  }
  if(!(params.pcolor2 == "" || params.pcolor2 == null)) {
    code += `--primary2: ${params.pcolor2};\n`;
  }
  if(!(params.bg1 == "" || params.bg1 == null)) {
    code += `--light: ${params.bg1};\n`;
  }
  if(!(params.bg2 == "" || params.bg2 == null)) {
    code += `--medium: ${params.bg2};\n`;
  }
  if(!(params.bg3 == "" || params.bg3 == null)) {
    code += `--dark: ${params.bg3};\n`;
  }

  code += "}";

  return code;
}

function hexToRgbA(hex){
    var c;
    if(/^#([A-Fa-f0-9]{3}){1,2}$/.test(hex)){
        c= hex.substring(1).split('');
        if(c.length== 3){
            c= [c[0], c[0], c[1], c[1], c[2], c[2]];
        }
        c= '0x'+c.join('');
        return 'rgba('+[(c>>16)&255, (c>>8)&255, c&255].join(',')+',.25)';
    }
}

async function updatePreview() {
  let hbBackground;
  if (document.getElementById('selectHbImage').value == "file") {
      hbBackground = await getBase64(document.getElementById('hbFile').files[0]);
  } else {hbBackground = document.getElementById('hbURL').value;}

  document.getElementById("preview").innerHTML = generateCode(hbBackground);
}

function changeValue(inputID, value) {
  document.getElementById(inputID).value = value;
  updatePreview();
}

function changePresetName() {
  document.getElementById('presetTitle').innerHTML = document.getElementById('presetName').value;
}

async function download() {
  var presetName = document.getElementById('themeName').value;

  if(presetName == "" || presetName == null){
    alert('Your theme is missing a name');
    return;
  } else {
    presetName = presetName.trim().replace(/ /gi, "_");
  }

  let code = `//META{"name":"${presetName}","description":"Generated by Spectra's Theme generator - Based on the Chemical Theme","author":"Spectra","version":"Auto Update"}*//\n`;
  code += '@import url("https://raw.githack.com/codedotspectra/themes/master/chemical/import/core.css");\n';
  code += generateMiniThemes();
  let hbBackground;
  if (document.getElementById('selectHbImage').value == "file") {
      hbBackground = await getBase64(document.getElementById('hbFile').files[0]);
  } else {hbBackground = document.getElementById('hbURL').value;}
  code += generateCode(hbBackground);

  dlFile('text/css', code, `${presetName}.theme.css`);
}

function dlFile(mime, text, name) {
    const blob = new Blob([new Uint8Array(text.split('').map(b => b.charCodeAt(0)))], {type: mime});
    if(navigator.msSaveBlob) return navigator.msSaveBlob(blob);

    const a = Object.assign(document.createElement('a'), {
        download: name,
        href: URL.createObjectURL(blob),
        style: { display: 'none' }
    });

    document.body.appendChild(a).click();
    a.remove();
    URL.revokeObjectURL(a.href);
}

async function updateMiniThemes() {
  document.getElementById('miniThemes').innerHTML = generateMiniThemes();
}

function generateMiniThemes() {
  let mt = "";

  if(document.getElementById('ccl').checked){
    mt += "@import url('https://raw.githack.com/codedotspectra/themes/master/mini-themes/compactChannelsList.css');\n";
  }
  if(document.getElementById('cml').checked) {
    mt += "@import url('https://raw.githack.com/codedotspectra/themes/master/mini-themes/compactMemberList.css');\n";
  }

  if(document.getElementById('dss').checked){
    mt += "@import url('https://raw.githack.com/codedotspectra/themes/master/mini-themes/normalSizeGuildIcons.css');\n";
  }

  if(document.getElementById('statusStyles').value == "rounded"){
    mt += "@import url('https://raw.githack.com/codedotspectra/themes/master/mini-themes/statusRounded.css');\n";
  } else if (document.getElementById('statusStyles').value == "squared") {
    mt += "@import url('https://raw.githack.com/codedotspectra/themes/master/mini-themes/statusSquared.css');\n";
  }

  return mt;
}

async function getBase64(file) {
    return new Promise((resolve, reject) => {
        let reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = () => resolve(reader.result);
        reader.onerror = error => reject(error);
    });
}

function mime(b64) {
    return b64.split(';')[0].split(':')[1];
}

async function verifyUrl(id) {
    let URL = document.getElementById(id).value;
    if(!(URL == "" || URL == null)){
      let urlEnd = URL.substring(URL.length-4, URL.length);
      if(!(urlEnd == ".jpg" || urlEnd == ".png" || urlEnd == ".gif" || urlEnd == "jpeg")){
        alert('-- invalid url --');
      } else {
        updatePreview();
      }
    }
}
async function verifyFile(id) {
    let file = await getBase64(document.getElementById(id).files[0]);
    if (mime(file).split('/')[0] != 'image') {
        alert('-- File is invalid --');
    } else {
        updatePreview();
    }
}


function selectImageMethod(id) {
  if(id == 'selectBImage') {
    if(document.getElementById(id).value == "url"){
      document.getElementById('bImageUrlInput').style.display = "block";
      document.getElementById('bImageFileInput').style.display = "none";
    } else {
      document.getElementById('bImageFileInput').style.display = "block";
      document.getElementById('bImageUrlInput').style.display = "none";
    }
  } else {
    if(document.getElementById(id).value == "url"){
      document.getElementById('hbImageUrlInput').style.display = "block";
      document.getElementById('hbImageFileInput').style.display = "none";
    } else {
      document.getElementById('hbImageFileInput').style.display = "block";
      document.getElementById('hbImageUrlInput').style.display = "none";
    }
  }
}
